suborgrepos:
  - ims-diagrams
  - test
repository:
  force_create: true
  auto_init: true
  license_template: mit
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: false
  default_branch: main
  topics:
    - ims
    - new-lable
