repository:
  name: ims-diagrams
  force_create: true
  auto_init: true
  description: set of IMS diagrams (MMD)
  homepage: https://example.github.io/
  topics:
    - ims
    - diagrams
  has_issues: false
  has_projects: false
  has_wiki: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  default_branch: main
branches:
  # applies to branch specified as `default_branch`
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        dismissal_restrictions:
#          users: []
#          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
#        apps: []
#        users: []
#        teams: []