repository:
  name: test
  gitignore_template: go
  description: test repo
  homepage: https://example.github.io/test
  private: false
  visibility: public
  has_issues: false
  has_projects: false
  has_wiki: false
branches:
  # applies to branch specified as `default_branch`
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
#        dismissal_restrictions:
#          users: ~
#          teams: ~
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        apps: ~
        users: ~
        teams: ~
