repository:
  name: test
  gitignore_template: go
  description: test repo
  homepage: https://example.github.io/test
  private: false
  visibility: public
  has_issues: false
  has_projects: false
  has_wiki: false
branches:
  - name: default # applies to branch specified as `default_branch`
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: true
      required_status_checks:
        strict: true
        contexts: [some-check]
      enforce_admins: true
      restrictions: ~
